### PR TITLE
implemented dinosaur support

### PR DESCRIPTION
**Pull request by tompave**
Correctly added dinosaur support, in compliance with what discussed a few hours ago.

### CODE REVIEW

**Comment by PericlesTheo** [comment]
emmm.... when was this discussed again? :)

**Comment by stevehassle** [comment]
https://s-media-cache-ak0.pinimg.com/originals/f1/42/33/f14233ce3621a1c49a8ad5218b05bc9e.jpg

**Comment by PericlesTheo** [comment]
yea.. as much as I'd love to have dinosaurs popping up on errors, I think will close this PR. Sorry @tompave :)

**Comment by tompave** [comment]
Not just in errors. The Dinosaur would have replaced any single operation.
Oh, well :-(

**Comment by tompave** [comment]
Hi @greysteil, since you are the new maintainer, are you going to re-consider this PR?

**Comment by greysteil** [comment]
Love this, but if Jurassic Park has taught me anything it's that these magnificent beasts belong in the past.

jurassic-world-trailer-still-3

**Comment by tompave** [comment]
> Love this, but if Jurassic Park has taught me anything it's that these magnificent beasts belong in the past.

Wrong.

> No, and let me be perfectly clear on this point. Dinosaurs lived 65 million years ago. What's left of them is fossilized in stone the actual scientists spend years to undercover.  
> What John Hammond and InGen created are theme park monsters. Nothing more, nothing less.
> (Dr. Alan Grant - [source](http://www.imsdb.com/scripts/Jurassic-Park-III.html))

You're welcome.

**Pull request closed without merging**
