### PR TITLE
Split out connection errors so they can be automatically retried

### PR DESCRIPTION
**Pull request by greysteil**
We've been seeing 504s from Onfido today and yesterday. This PR splits out connection errors and timeouts from `RequestErrors`, so that they can be caught and dealt with separately.

It's a major refactor of how responses are processed, but should only be breaking in one small way: connection errors and errors with an unparseable body will now be raised even if `throws_exceptions` is set to false. The alternative was to write JSON messages for these cases, but that seemed excessive.

### CODE REVIEW

**Comment by greysteil** [comment]
@PericlesTheo - what do you reckon? Also, are you looking for maintainers for this gem? We're using it in production at GoCardless and I'd be happy to help improve it.

**Comment by PericlesTheo** [comment]
Hey @greysteil thanks for the PR. I'm not a maintainer anymore - haven't been so for a couple of months now since I left Hassle.

I've contacted the devs @ Hassle to update the maintainers in the gemspec so it's transparent who you need to contact instead :)

**Comment by stevehassle** [comment]
Hi @greysteil , thanks for that, have added you to this project to take over its maintenance if you wish

**Comment by greysteil** [comment]
Awesome, thanks @stevehassle

**Pull request merged**
